### ISSUE TITLE
add cross icon to mobile navbar

### ISSUE THREAD

**Issue by jainaryan04** [SaranshBangar/Daneizo#51]
add a cross-icon to the mobile navbar to allow to user to close it.
please add gssoc-ext and hacktoberfest-accepted labels and assign it to me @SaranshBangar 

![image](https://github.com/user-attachments/assets/d60459b1-7f8d-408f-803a-ed3ca15a5a9c)

**Comment by Athaxv** [comment]
please assign this task to me

**Comment by jangirvipin** [comment]
please assign it to me

**Comment by SaranshBangar** [comment]
@jainaryan04 You can proceed with it. Please remember to -

1. Send a photo here of of the new design before raising a PR
2. Follow the proper file structure
3. Star the repo :)

All the best!

@Athaxv and @jangirvipin, I am sorry but since @jainaryan04 raised the issue, it his right to raise a PR for the same as well 😓

**Comment by jainaryan04** [comment]
@SaranshBangar Please review and let me know if I can go ahead with the PR

![image](https://github.com/user-attachments/assets/ea462a30-1c61-471c-b428-de7e0952c625)

**Comment by SaranshBangar** [comment]
@jainaryan04 Yup, you can raise the PR
